# Generated by Django 3.1.4 on 2021-01-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210105_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='文章配图'),
        ),
    ]
